### ISSUE TITLE
Working for Moodle?

### ISSUE THREAD

**Issue by willhallonline** [Dropa/moodlecs#1]
Hey. Does this work for Moodle? If so, I might add to another of my pet projects. I have no background in Moodle, so not sure if appropriate or not 😸

**Comment by Dropa** [comment]
Hey Will!

Indeed it does work! We're using it as part of pipeline in GitLab with following script
```yaml
  script:
    - CHANGED_FILES=$(git diff --name-only --diff-filter=d origin/master... .  |tr '\n' ' ')
    - if [ -n "$CHANGED_FILES" ]; then phpcs --ignore=amd/build/*,js/*,css/*,tests/*,vendor/* $CHANGED_FILES; else echo "No changed custom files"; fi
```

So it is quite similar on how we actually use your version of Drupal phpcs.

**Comment by willhallonline** [comment]
That is cool. I use GitLab too, both at work and personally, however, I haven't thought of scripting is more. That looks quite useful. I'll close the issue too 👍
